# Generated by Django 4.1.5 on 2023-01-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Filiacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provincia", models.CharField(blank=True, max_length=20, null=True)),
                ("distrito", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "tipo_municipalidad",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "documento_identidad",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "apellido_paterno",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "apellido_materno",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("nombres", models.CharField(blank=True, max_length=200, null=True)),
                ("telefono", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "correo_electronico",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("perfil", models.CharField(blank=True, max_length=100, null=True)),
                ("condicion", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "cuenta_usuario",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "contraseña_usuario",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("req_oficio", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "req_resolucion",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "req_formato",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "req_generales_excel",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
    ]
