# Generated by Django 4.1.5 on 2023-01-20 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filiacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(max_length=20)),
                ('historia_clinica', models.CharField(max_length=20)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('nombres', models.CharField(max_length=100)),
                ('direccion_reniec', models.CharField(max_length=200)),
                ('direccion_declarado', models.CharField(max_length=200)),
                ('ubigeo_reniec', models.CharField(max_length=200)),
                ('ubigeo_declarado', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.CharField(max_length=100)),
                ('edad', models.CharField(max_length=100)),
                ('fecha_ultima_regla', models.CharField(max_length=100)),
                ('fecha_probable_parto', models.CharField(max_length=100)),
                ('numero_telefono', models.CharField(max_length=100)),
                ('id_establecimiento', models.CharField(max_length=100)),
            ],
        ),
    ]
