# Generated by Django 4.1.5 on 2023-02-01 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Filiacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provincia", models.CharField(blank=True, max_length=100, null=True)),
                ("distrito", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "tipo_municipalidad",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Provincial", "Provincial"),
                            ("Distrital", "Distrital"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "documento_identidad",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "apellido_paterno",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "apellido_materno",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("nombres", models.CharField(blank=True, max_length=200, null=True)),
                ("telefono", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "correo_electronico",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "perfil",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Consultor", "Consultor"),
                            ("Registrador", "Registrador"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "condicion",
                    models.CharField(
                        blank=True,
                        choices=[("Alta", "Alta"), ("Baja", "Baja")],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "cuenta_usuario",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Si", "Si"),
                            ("No", "No"),
                            ("Espera respuesta MINSA", "Espera respuesta MINSA"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "contraseña_usuario",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "req_formato",
                    models.FileField(
                        blank=True, null=True, upload_to="filiacion/formato/"
                    ),
                ),
                (
                    "dateTimeOfUpload_req_formato",
                    models.DateTimeField(auto_now=True, null=True),
                ),
                (
                    "req_generales_excel",
                    models.FileField(
                        blank=True, null=True, upload_to="filiacion/excel/"
                    ),
                ),
                (
                    "dateTimeOfUpload_generales_excel",
                    models.DateTimeField(auto_now=True, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Provincia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_provincia",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("ubigeo", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Red",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_red",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "cod_red",
                    models.CharField(blank=True, default="", max_length=10, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Microred",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_microred",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "cod_mic",
                    models.CharField(blank=True, default="", max_length=10, null=True),
                ),
                (
                    "cod_red",
                    models.CharField(blank=True, default="", max_length=10, null=True),
                ),
                (
                    "red",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redes",
                        to="filiacion.red",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Establecimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_establecimiento",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "codigo_unico",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "microred",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="microredes",
                        to="filiacion.microred",
                    ),
                ),
                (
                    "red",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="filiacion.red",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Distrito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_distrito",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("ubigeo", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "provincia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provincias",
                        to="filiacion.provincia",
                    ),
                ),
            ],
        ),
    ]
