# Generated by Django 4.1.5 on 2023-02-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filiacion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Directorio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("diresa", models.CharField(blank=True, max_length=100, null=True)),
                ("red", models.CharField(blank=True, max_length=100, null=True)),
                ("microred", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "establecimiento",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "tipo_usuario",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("diresa", "diresa"),
                            ("red", "red"),
                            ("microred", "microred"),
                            ("establecimiento", "establecimiento"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "documento_identidad",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "apellido_paterno",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "apellido_materno",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("nombres", models.CharField(blank=True, max_length=200, null=True)),
                ("telefono", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "correo_electronico",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "perfil",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Consultor", "Consultor"),
                            ("Registrador", "Registrador"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "condicion",
                    models.CharField(
                        blank=True,
                        choices=[("Alta", "Alta"), ("Baja", "Baja")],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "cuenta_usuario",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Si", "Si"),
                            ("No", "No"),
                            ("Espera respuesta MINSA", "Espera respuesta MINSA"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "contraseña_usuario",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "req_formato",
                    models.FileField(
                        blank=True, null=True, upload_to="filiacion/formato/"
                    ),
                ),
                (
                    "dateTimeOfUpload_req_formato",
                    models.DateTimeField(auto_now=True, null=True),
                ),
                (
                    "req_generales_excel",
                    models.FileField(
                        blank=True, null=True, upload_to="filiacion/excel/"
                    ),
                ),
                (
                    "dateTimeOfUpload_generales_excel",
                    models.DateTimeField(auto_now=True, null=True),
                ),
            ],
        ),
    ]
