# Generated by Django 4.1.5 on 2023-01-27 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("filiacion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Provincia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_provincia",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("ubigeo", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Red",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_red",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "cod_red",
                    models.CharField(blank=True, default="", max_length=10, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Microred",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_microred",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "cod_mic",
                    models.CharField(blank=True, default="", max_length=10, null=True),
                ),
                (
                    "cod_red",
                    models.CharField(blank=True, default="", max_length=10, null=True),
                ),
                (
                    "red",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redes",
                        to="filiacion.red",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Establecimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_establecimiento",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "codigo_unico",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "microred",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="microredes",
                        to="filiacion.microred",
                    ),
                ),
                (
                    "red",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="filiacion.red",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Distrito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_distrito",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("ubigeo", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "provincia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provincias",
                        to="filiacion.provincia",
                    ),
                ),
            ],
        ),
    ]
