# Generated by Django 4.1.5 on 2023-01-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "filiacion",
            "0003_alter_filiacion_distrito_alter_filiacion_provincia_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="filiacion",
            name="tipo_municipalidad",
            field=models.CharField(
                blank=True,
                choices=[("Provincial", "Provincial"), ("Distrital", "Distrital")],
                max_length=100,
                null=True,
            ),
        ),
    ]
