# Generated by Django 4.1.5 on 2023-01-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filiacion", "0004_alter_filiacion_tipo_municipalidad"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filiacion",
            name="condicion",
            field=models.CharField(
                blank=True,
                choices=[(1, "Alta"), (2, "Baja")],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="filiacion",
            name="cuenta_usuario",
            field=models.CharField(
                blank=True,
                choices=[(1, "Si"), (2, "No"), (3, "Espera respuesta MINSA")],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="filiacion",
            name="perfil",
            field=models.CharField(
                blank=True,
                choices=[(1, "Consultor"), (2, "Registrador")],
                max_length=100,
                null=True,
            ),
        ),
    ]
