# Generated by Django 4.1.5 on 2023-01-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filiacion", "0005_alter_filiacion_condicion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filiacion",
            name="condicion",
            field=models.CharField(
                blank=True,
                choices=[("Alta", "Alta"), ("Baja", "Baja")],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="filiacion",
            name="cuenta_usuario",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Si", "Si"),
                    ("No", "No"),
                    ("Espera respuesta MINSA", "Espera respuesta MINSA"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="filiacion",
            name="perfil",
            field=models.CharField(
                blank=True,
                choices=[("Consultor", "Consultor"), ("Registrador", "Registrador")],
                max_length=100,
                null=True,
            ),
        ),
    ]
