# Generated by Django 4.1.5 on 2023-01-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filiacion", "0006_alter_filiacion_condicion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filiacion",
            name="req_formato",
            field=models.FileField(
                blank=True, null=True, upload_to="filiacion/formato/"
            ),
        ),
        migrations.AlterField(
            model_name="filiacion",
            name="req_generales_excel",
            field=models.FileField(blank=True, null=True, upload_to="filiacion/excel/"),
        ),
        migrations.AlterField(
            model_name="filiacion",
            name="req_oficio",
            field=models.FileField(
                blank=True, null=True, upload_to="filiacion/oficio/"
            ),
        ),
        migrations.AlterField(
            model_name="filiacion",
            name="req_resolucion",
            field=models.FileField(
                blank=True, null=True, upload_to="filiacion/resolucion/"
            ),
        ),
    ]
