# Generated by Django 4.1.5 on 2023-01-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filiacion", "0008_alter_filiacion_req_formato_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="filiacion",
            name="dateTimeOfUpload_generales_excel",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="filiacion",
            name="dateTimeOfUpload_req_formato",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="filiacion",
            name="dateTimeOfUpload_req_oficio",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="filiacion",
            name="dateTimeOfUpload_req_resolucion",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="filiacion",
            name="req_formato",
            field=models.FileField(upload_to="f_formato/"),
        ),
        migrations.AlterField(
            model_name="filiacion",
            name="req_generales_excel",
            field=models.FileField(upload_to="f_excel/"),
        ),
        migrations.AlterField(
            model_name="filiacion",
            name="req_oficio",
            field=models.FileField(upload_to="filiacion/"),
        ),
        migrations.AlterField(
            model_name="filiacion",
            name="req_resolucion",
            field=models.FileField(upload_to="f_resolucion/"),
        ),
    ]
