# Generated by Django 4.1.5 on 2023-01-30 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filiacion", "0011_alter_filiacion_distrito_alter_filiacion_provincia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filiacion",
            name="distrito",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="filiacion",
            name="provincia",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="filiacion",
            name="req_formato",
            field=models.FileField(
                blank=True, null=True, upload_to="filiacion/formato/"
            ),
        ),
        migrations.AlterField(
            model_name="filiacion",
            name="req_generales_excel",
            field=models.FileField(blank=True, null=True, upload_to="filiacion/excel/"),
        ),
        migrations.AlterField(
            model_name="filiacion",
            name="req_oficio",
            field=models.FileField(blank=True, null=True, upload_to="filiacion/oficio"),
        ),
        migrations.AlterField(
            model_name="filiacion",
            name="req_resolucion",
            field=models.FileField(
                blank=True, null=True, upload_to="filiacion/resolucion/"
            ),
        ),
    ]
